Pass GIT_COMMIT to lint script

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -17,6 +17,16 @@ function lint() {
     ./scripts/lint
 }
 
+function lint_ci() {
+    if [[ -n "${GIT_COMMIT}" ]]; then
+        GIT_COMMIT="${GIT_COMMIT}" \
+            ./scripts/lint --ci
+    else
+        echo "ERROR: No GIT_COMMIT variable defined."
+        exit 1
+    fi
+}
+
 function test_django() {
     docker-compose \
         run --rm --entrypoint python django \
@@ -52,7 +62,7 @@ if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
     elif [ "${1:-}" = "--django" ]; then
         test_django
     elif [ "${1:-}" = "--ci" ]; then
-        lint
+        lint_ci
         test_app
         test_django_ci
     else
